Update main2.yml

diff --git a/.github/workflows/main2.yml b/.github/workflows/main2.yml
--- a/.github/workflows/main2.yml
+++ b/.github/workflows/main2.yml
@@ -1,44 +1,44 @@
-name: rebase reuse
+# name: rebase reuse
 
-on:
-  workflow_call:
-    # inputs:
-    #   base_branch:
-    #     required: true
-    #     type: string
-    # secrets:
-    #   token:
-    #     required: true
+# on:
+#   workflow_call:
+#     # inputs:
+#     #   base_branch:
+#     #     required: true
+#     #     type: string
+#     # secrets:
+#     #   token:
+#     #     required: true
         
-jobs:
+# jobs:
 
-  check-rebase:
-    runs-on: ubuntu-latest
-    steps:
+#   check-rebase:
+#     runs-on: ubuntu-latest
+#     steps:
     
-      - name: Checkout code
-        uses: actions/checkout@v3
-        # with:
-        #   fetch-depth: 0
-        #   token: ${{inputs.token }}
+#       - name: Checkout code
+#         uses: actions/checkout@v3
+#         # with:
+#         #   fetch-depth: 0
+#         #   token: ${{inputs.token }}
 
-      - name: Check if branch is rebased
-        run: |
-          #!/bin/bash
+#       - name: Check if branch is rebased
+#         run: |
+#           #!/bin/bash
           
-          git_hash=$(git rev-parse "$GITHUB_SHA")
-          echo "Branch commit: $git_hash"
+#           git_hash=$(git rev-parse "$GITHUB_SHA")
+#           echo "Branch commit: $git_hash"
 
-          main_head=$(git rev-parse origin/main)
-          echo "Trunk head: $main_head"
+#           main_head=$(git rev-parse origin/main)
+#           echo "Trunk head: $main_head"
 
-          branch_source_commit_id="$(git merge-base "$git_hash" origin/main)"
-          echo "First commir of this branch: $branch_source_commit_id"
+#           branch_source_commit_id="$(git merge-base "$git_hash" origin/main)"
+#           echo "First commir of this branch: $branch_source_commit_id"
 
-          if [[ "$branch_source_commit_id" != "$main_head" ]]; then
-            echo "Error: you need to rebase your branch with head main."
-            exit 1
-          fi
+#           if [[ "$branch_source_commit_id" != "$main_head" ]]; then
+#             echo "Error: you need to rebase your branch with head main."
+#             exit 1
+#           fi
 
 
 
